# Generated by Django 2.1.5 on 2019-01-22 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audioView', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_score', models.IntegerField()),
                ('subreddit_rank', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('date_period_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audioView.DatePeriod')),
                ('subreddit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audioView.Subreddit')),
            ],
        ),
    ]
