# Generated by Django 2.1.5 on 2019-01-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioView', '0002_dateperiod_subreddit_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
